import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Menu, X, ArrowUpRight, Truck, Sparkles, Clock3, Shirt, MapPin, Phone, Mail, Check, ChevronDown, ShieldCheck, Leaf, PackageCheck} from 'lucide-react';
import './styles.css';
import './polish.css';
import AdminDashboard from './AdminDashboard.jsx';
import BookingForm from './BookingForm.jsx';
import ReceiptPage from './ReceiptPage.jsx';

const services=[
  {icon:Sparkles,n:'Wash & fold',d:'Everyday laundry, expertly sorted, washed, dried and neatly folded.',p:'From KSh 1,200 / load'},
  {icon:Shirt,n:'Dry cleaning',d:'Careful treatment for suits, dresses, delicate fabrics and special garments.',p:'Priced per item'},
  {icon:Clock3,n:'Ironing & steaming',d:'Crisp, polished finishing for your wardrobe, uniforms and linens.',p:'From KSh 700 / load'},
  {icon:Truck,n:'Pickup & delivery',d:'Door-to-door convenience across Kitengela, Kisaju, Isinya and Athi River.',p:'Available daily'}
];
const defaultSteps=['We collect','We sort','We clean','We finish','We deliver'];
const priceGroups=[
 {t:'Full load services',items:[['Washing','600'],['Drying','600'],['Ironing','700'],['Wash, dry & fold','1,200'],['Wash, dry, iron & hang','1,700'],['Excess per kilo','140']]},
 {t:'Popular items',items:[['T-shirt','200'],['Shirt / blouse / skirt','200'],['Trouser / dress','200'],['Track suit','300'],['Jacket — normal','300'],['Suit — two piece','700']]},
 {t:'Home essentials',items:[['Duvet cover','300'],['Bedsheet — each','200'],['Curtains per kg','300'],['Pillow','200'],['Towel','200'],['Duvet / blanket 2kg','700']]}
];

function App(){
 const [open,setOpen]=useState(false); const [prices,setPrices]=useState(false); const [processSteps,setProcessSteps]=useState(defaultSteps); const [siteSettings,setSiteSettings]=useState(null);
 useEffect(()=>{fetch('/api/process').then(r=>r.ok?r.json():Promise.reject()).then(data=>setProcessSteps(data.steps)).catch(()=>{});},[]);
 useEffect(()=>{fetch('/api/site-settings').then(r=>r.ok?r.json():Promise.reject()).then(data=>{setSiteSettings(data);document.title=data.seo.title;document.querySelector('meta[name="description"]')?.setAttribute('content',data.seo.description)}).catch(()=>{});},[]);
 const nav=['services','process','pricing','about','contact'];
 return <>
  <div className="topbar"><span>Express wash in just 4 hours</span><span>Chuna Mall · Shop 10 · Kitengela</span></div>
  <header><a className="brand" href="#home"><span className="logo-crop"><img src="/assets/logo.jpg" alt="Open Doors Laundromat logo"/></span><span>OPEN DOORS<small>LAUNDROMAT</small></span></a>
   <nav className={open?'open':''}>{nav.map(n=><a key={n} href={'#'+n} onClick={()=>setOpen(false)}>{n}</a>)}<a className="nav-cta" href="#booking" onClick={()=>setOpen(false)}>Book a pickup</a></nav>
   <button className="menu" onClick={()=>setOpen(!open)} aria-label="Toggle menu">{open?<X/>:<Menu/>}</button>
  </header>
  <main>
   <section className="hero" id="home"><div className="hero-copy"><div className="hero-kicker"><span>Since 2025</span><p className="eyebrow">Laundry day, handled.</p></div><h1>Fresh clothes.<br/><em>More time for you.</em></h1><p className="lede">Premium laundry and garment care for homes, businesses and hospitality clients—collected, cared for and delivered.</p><div className="actions"><a className="primary" href="#booking">Schedule a pickup <ArrowUpRight/></a><a className="secondary" href="#pricing">View prices</a></div><div className="trust"><b>4 hrs</b><span>Express turnaround</span><a className="admin-shortcut" href="/admin" aria-label="Open admin login">24 hrs</a><span>Standard service</span></div></div>
    <div className="hero-visual"><span className="wash-mark">WASH · DRY · FOLD</span><img src="/assets/laundry-machines.jpg" alt="Professional laundry facility"/><div className="floating"><span><Check/>Pickup available</span><b>Kisaju · Kitengela<br/>Isinya · Athi River</b></div></div>
   </section>
   <section className="benefits" aria-label="Service benefits"><div><ShieldCheck/><span><b>Professional care</b><small>Handled with precision</small></span></div><div><Clock3/><span><b>Fast turnaround</b><small>Same-day service available</small></span></div><div><PackageCheck/><span><b>Pickup & delivery</b><small>Convenience at your door</small></span></div><div><Leaf/><span><b>Fabric conscious</b><small>Care matched to every item</small></span></div></section>
   <section id="services" className="section"><div className="section-head"><div><p className="eyebrow">Thoughtful garment care</p><h2>Everything laundry needs.</h2></div><p>From everyday loads to delicate occasion wear, every item gets the right process and a quality check.</p></div><div className="service-grid">{services.map(({icon:Icon,n,d,p},i)=><article key={n}><span className="num">0{i+1}</span><Icon/><h3>{n}</h3><p>{d}</p><small>{p}</small></article>)}</div></section>
   <section id="process" className="process"><div className="process-image"><img src="/assets/process.jpg" alt="Open Doors care process"/></div><div className="process-copy"><p className="eyebrow">Our process</p><h2>Care in every step.</h2><p>We inspect, sort and treat each order according to its fabric and care needs. Nothing rushed. Nothing overlooked.</p><ol>{processSteps.map((s,i)=><li key={`${s}-${i}`}><b>{String(i+1).padStart(2,'0')}</b><span>{s}</span></li>)}</ol></div></section>
   <section id="pricing" className="section pricing"><div className="section-head"><div><p className="eyebrow">Clear, honest pricing</p><h2>Know before you load.</h2></div><p>Prices in Kenyan shillings. Children’s single items are charged at half the adult rate.</p></div><div className="price-grid">{(siteSettings?.priceGroups||priceGroups).map(g=><article key={g.t}><h3>{g.t}</h3>{g.items.map(x=><div className="price-row" key={x[0]}><span>{x[0]}</span><b>KSh {x[1]}</b></div>)}</article>)}</div><button className="all-prices" onClick={()=>setPrices(!prices)}>More item prices <ChevronDown className={prices?'flip':''}/></button>{prices&&<div className="more-prices"><span>Wedding gown <b>KSh 1,500–3,000</b></span><span>Leather jacket <b>KSh 1,500</b></span><span>School blazer <b>KSh 300</b></span><span>Three-piece suit <b>KSh 800</b></span><span>Blanket 4kg <b>KSh 1,000</b></span><span>Sheers per kg <b>KSh 200</b></span></div>}<figure className="pricing-guide"><img src="/assets/pricing-guide-full.jpg" alt="Complete Open Doors Laundromat pricing guide"/><figcaption>Full pricing guide — tap or click to view clearly</figcaption></figure><p className="note">A 7kg load is approximately 25 shirts or 14 trousers. Single-unit children’s clothing is half price.</p></section>
   <section id="about" className="about"><div><p className="eyebrow">Built around your time</p><h2>More than clean clothes.</h2><p>Founded in 2025, Open Doors was created to make professional garment care reliable, affordable and genuinely convenient.</p><blockquote>“We’re here to give our clients back what matters most—time, comfort and peace of mind.”</blockquote><p className="founder">Elizabeth Wanjiru Njoroge <span>Founder & proprietor</span></p></div><img src="/assets/quality.jpg" alt="Open Doors Laundromat storefront"/></section>
   <section id="contact" className="contact"><div className="contact-copy"><p className="eyebrow light">Ready when you are</p><h2>Let us take laundry off your list.</h2><p>Book a pickup, ask about a garment, or drop by our Kitengela shop.</p><a className="contact-link" href="tel:+254119444972"><Phone/> 011 944 4972</a><a className="contact-link" href="mailto:opendoorslaundromat@gmail.com"><Mail/> opendoorslaundromat@gmail.com</a><a className="contact-link" target="_blank" href="https://www.google.com/maps/search/?api=1&query=Chuna+Mall+Kitengela"><MapPin/> Chuna Mall, Ground Floor, Shop 10</a></div><div className="hours"><h3>Opening hours</h3><div><span>Monday – Saturday</span><b>8:00 am – 9:00 pm</b></div><div><span>Sunday</span><b>2:00 pm – 7:00 pm</b></div><div><span>Public holidays</span><b>9:00 am – 7:00 pm</b></div><a href="https://wa.me/254119444972" target="_blank">Chat on WhatsApp <ArrowUpRight/></a></div></section>
   <BookingForm/>
  </main>
  <footer><div className="footer-main"><div className="footer-intro"><div className="brand footer-brand"><span className="logo-crop"><img src="/assets/logo.jpg" alt="Open Doors Laundromat logo"/></span><span>OPEN DOORS<small>LAUNDROMAT</small></span></div><p>Professional garment care that gives you back more time for the things that matter.</p><a className="footer-cta" href="https://wa.me/254119444972" target="_blank">Book a pickup <ArrowUpRight/></a></div><div className="footer-column"><h3>Explore</h3><a href="#services">Our services</a><a href="#process">How it works</a><a href="#pricing">Pricing guide</a><a href="#about">Our story</a></div><div className="footer-column"><h3>Visit us</h3><p>Chuna Mall, Ground Floor<br/>Shop 10, Kitengela</p><a href="tel:+254119444972">011 944 4972</a><a href="mailto:opendoorslaundromat@gmail.com">Email us</a></div><div className="footer-column"><h3>Service hours</h3><p>Mon – Sat<br/><b>8:00 am – 9:00 pm</b></p><p>Sunday<br/><b>2:00 pm – 7:00 pm</b></p></div></div><div className="footer-bottom"><p>© 2026 Open Doors Laundromat</p><p className="footer-tagline">So fresh, so clean, so you.</p><a href="#home">Back to top ↑</a></div></footer>
 </>
}

function AdminApp(){
 const [authenticated,setAuthenticated]=useState(false); const [checking,setChecking]=useState(true); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [steps,setSteps]=useState(defaultSteps); const [message,setMessage]=useState(''); const [saving,setSaving]=useState(false);
 useEffect(()=>{Promise.all([fetch('/api/admin/session'),fetch('/api/process')]).then(async([session,process])=>{setAuthenticated(session.ok);if(process.ok)setSteps((await process.json()).steps)}).finally(()=>setChecking(false));},[]);
 async function login(e){e.preventDefault();setMessage('');const response=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const data=await response.json();if(!response.ok)return setMessage(data.error);setAuthenticated(true);setPassword('');}
 async function save(e){e.preventDefault();setSaving(true);setMessage('');const response=await fetch('/api/admin/process',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({steps})});const data=await response.json();setSaving(false);setMessage(response.ok?'Process updated successfully.':data.error);}
 async function logout(){await fetch('/api/admin/logout',{method:'POST'});setAuthenticated(false);setEmail('');}
 function updateStep(index,value){setSteps(current=>current.map((step,i)=>i===index?value:step));}
 if(checking)return <div className="admin-shell"><p>Loading admin…</p></div>;
 return <div className="admin-shell"><a className="admin-brand" href="/"><span className="logo-crop"><img src="/assets/logo.jpg" alt="Open Doors logo"/></span><span>OPEN DOORS<small>ADMIN PORTAL</small></span></a>{!authenticated?<main className="admin-card"><p className="eyebrow">Secure access</p><h1>Welcome back.</h1><p>Sign in to manage the laundry care process shown on the website.</p><form onSubmit={login}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="username"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password"/></label>{message&&<p className="admin-message error">{message}</p>}<button type="submit">Sign in <ArrowUpRight/></button></form></main>:<main className="admin-panel"><div className="admin-heading"><div><p className="eyebrow">Website content</p><h1>Edit the process</h1><p>Changes appear in the “Care in every step” section.</p></div><button className="logout" onClick={logout}>Log out</button></div><form onSubmit={save}><div className="step-editor">{steps.map((step,index)=><div className="step-input" key={index}><span>{String(index+1).padStart(2,'0')}</span><input value={step} maxLength="80" onChange={e=>updateStep(index,e.target.value)} aria-label={`Process step ${index+1}`}/><button type="button" onClick={()=>setSteps(current=>current.filter((_,i)=>i!==index))} disabled={steps.length<=2} aria-label={`Remove step ${index+1}`}><X/></button></div>)}</div><button className="add-step" type="button" disabled={steps.length>=12} onClick={()=>setSteps(current=>[...current,'New process step'])}>+ Add step</button>{message&&<p className={`admin-message ${message.includes('successfully')?'success':'error'}`}>{message}</p>}<button className="save-button" type="submit" disabled={saving}>{saving?'Saving…':'Save changes'} <Check/></button></form></main>}</div>
}

createRoot(document.getElementById('root')).render(window.location.pathname.startsWith('/receipt/')?<ReceiptPage/>:window.location.pathname.startsWith('/admin')?<AdminDashboard/>:<App/>);
