import React,{useEffect,useState} from 'react';
import {ArrowLeft, Printer} from 'lucide-react';

export default function ReceiptPage(){
 const [receipt,setReceipt]=useState(null),[error,setError]=useState('');
 const token=window.location.pathname.split('/').filter(Boolean).at(-1);
 useEffect(()=>{fetch(`/api/receipts/${encodeURIComponent(token)}`).then(async response=>{if(!response.ok)throw new Error((await response.json()).error);return response.json()}).then(setReceipt).catch(error=>setError(error.message))},[token]);
 if(error)return <main className="receipt-state"><h1>{error}</h1><a href="/"><ArrowLeft/> Back to website</a></main>;
 if(!receipt)return <main className="receipt-state"><p>Preparing your receipt…</p></main>;
 return <main className="receipt-page"><div className="receipt-actions"><a href="/"><ArrowLeft/> Website</a><button onClick={()=>window.print()}><Printer/> Print / save PDF</button></div><article className="receipt"><header><div className="receipt-brand"><span className="receipt-logo"><img src="/assets/logo.jpg" alt="Open Doors Laundromat logo"/></span><div><h1>OPEN DOORS</h1><p>LAUNDROMAT</p></div></div><div className="receipt-title"><span>REQUEST RECEIPT</span><b>{receipt.receiptNumber}</b></div></header><section className="receipt-meta"><div><small>Issued to</small><b>{receipt.name}</b><span>{receipt.phone}</span></div><div><small>Date issued</small><b>{new Date(receipt.createdAt).toLocaleDateString('en-KE',{dateStyle:'medium'})}</b><span>{new Date(receipt.createdAt).toLocaleTimeString('en-KE',{hour:'2-digit',minute:'2-digit'})}</span></div></section><section className="receipt-service"><div><small>Requested services</small><h2>{receipt.items?.length||1} service item{receipt.items?.length===1?'':'s'}</h2></div><span className={`receipt-status ${receipt.status}`}>{receipt.status}</span></section>{receipt.items?.length?<section className="receipt-lines"><div className="receipt-line heading"><span>Service</span><span>Kg / Qty</span><span>Price</span><span>Subtotal</span></div>{receipt.items.map((item,index)=><div className="receipt-line" key={index}><b>{item.service}</b><span>{item.kg}</span><span>KSh {item.priceLabel}</span><b>KSh {item.subtotal.toLocaleString()}</b></div>)}<div className="receipt-total"><span>Estimated total</span><b>KSh {receipt.estimatedTotal.toLocaleString()}</b></div></section>:null}<section className="receipt-details"><div className="receipt-payment"><small>Mode of payment</small><p><b>{receipt.paymentMethod||'Not selected'}</b>{receipt.paymentMethod==='M-Pesa'&&receipt.mpesaPhone?<span>M-Pesa prompt number: {receipt.mpesaPhone}</span>:null}</p></div><div><small>Pickup area</small><p>{receipt.location||'To be confirmed'}</p></div><div><small>Additional details</small><p>{receipt.notes||'No additional details provided.'}</p></div></section><footer><div><b>Thank you for choosing Open Doors.</b><p>This receipt confirms your service request. Final charges are confirmed after item inspection.</p></div><div className="receipt-contact"><span>011 944 4972</span><span>Chuna Mall · Shop 10 · Kitengela</span></div></footer></article><p className="receipt-footnote">So fresh, so clean, so you.</p></main>
}
